@extends('master')

@section('title', 'About')

@section('main')
<div class="container">
    <h2 class="text-center">About Coding Blog</h2>
    <p class="text-justify">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni quas enim doloremque numquam libero! Ullam neque corrupti, reprehenderit nihil nisi praesentium aut veritatis rerum at inventore adipisci! Est adipisci totam error accusantium inventore ut perferendis doloribus hic facilis vero maiores exercitationem ipsum veniam, ipsa, aspernatur magni illo. Illo labore, dolorem in, sed recusandae, ratione voluptatem reiciendis aliquid debitis nihil velit quaerat perspiciatis sapiente veritatis vel nulla repudiandae nesciunt? Id nesciunt numquam quibusdam? Voluptatum cumque laudantium expedita quos, ea officiis, officia quam odit, suscipit enim ipsam eaque commodi doloremque et labore. Voluptatibus eum necessitatibus ullam tenetur accusantium amet eveniet, iusto nam quibusdam harum quos minus distinctio autem! Nam asperiores autem eligendi modi sapiente delectus laudantium dignissimos. Accusamus cumque illum eveniet velit officiis nisi, molestias libero eius quia tenetur! Accusantium enim veritatis, neque omnis culpa, quidem ea recusandae, mollitia quibusdam asperiores totam ad. Molestiae, quibusdam, cumque quas eaque quam assumenda ex totam cupiditate aliquid animi, voluptate vero quidem molestias commodi. Vero architecto labore temporibus fugit quisquam eum odit exercitationem natus illo nam sint nulla veritatis facere quis in, nostrum, nisi enim sequi nemo corrupti a ullam? Atque aspernatur error deleniti, ad iusto consequatur praesentium nobis voluptatem neque sed quibusdam, impedit eveniet eaque maxime voluptas aliquid non sequi recusandae a voluptate minima esse rem! Autem, atque nesciunt earum qui cupiditate accusantium error corrupti beatae animi possimus necessitatibus vero, asperiores ratione, incidunt hic maiores voluptatem officiis dolor nihil aliquid. Eaque blanditiis explicabo pariatur, architecto voluptatem beatae quasi ipsa quis voluptatum quisquam ea facilis nostrum? Asperiores molestiae itaque quas corrupti quisquam pariatur dolore perferendis cum iste ullam, commodi iusto inventore repellat nemo voluptatem ipsa dignissimos vel suscipit. Possimus obcaecati itaque odit quae placeat asperiores laborum a rerum nesciunt, quod, perspiciatis nemo ducimus sapiente repudiandae quaerat maxime quia iure eos. Deleniti consequuntur soluta praesentium fugiat omnis veritatis voluptas, similique nobis ad nesciunt consequatur ex? Aliquid accusamus ipsa quisquam tempore atque quod voluptatibus neque deleniti natus dolorum obcaecati eveniet consectetur nobis eaque praesentium reprehenderit velit molestiae libero, nam asperiores et totam beatae ea nostrum. Aliquid nihil perferendis reprehenderit explicabo adipisci. Optio odio consequuntur repellat dicta nam ipsam tempore impedit sed exercitationem illum et ducimus adipisci, aliquam ut nemo, quam magni dolorum eum dolore dolorem vel ad quae? Tempora consequatur adipisci architecto dolore</p>
</div>
@endsection